#!/bin/bash

# Set X server settings
xset -dpms
xset s off
xset s noblank

# Set up Xauthority
[ ! -d "/home/user/xauthority" ] && mkdir -p "/home/user/xauthority"
touch /home/user/xauthority/.xauth
xauth -i -f /home/user/xauthority/.xauth generate :0 . trusted
chown -R user:users /home/user/xauthority

# Start icewm-session-lite
exec icewm-session-lite
