#!/bin/bash
echo "xinitrc script started" > /var/log/xinitrc.log

xset -dpms
xset s off
xset s noblank

[ ! -d "/home/user/xauthority" ] && mkdir -p "/home/user/xauthority"
touch /home/user/xauthority/.xauth
xauth -i -f /home/user/xauthority/.xauth generate :0 . trusted
chown -R user:users /home/user/xauthority

# Log before starting icewm-session-lite
echo "Starting icewm-session-lite" >> /var/log/xinitrc.log

exec icewm-session-lite

# This should never be reached unless icewm-session-lite exits
echo "icewm-session-lite exited" >> /var/log/xinitrc.log